name: aptible

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Deploy to Aptible
      uses: aptible/aptible-deploy-action@v4
      with:
        type: git
        app: mtgplayer
        environment: mtgplayer
        username: ${{ secrets.m.rfischer5235@gmail.com }}
        password: ${{ secrets.DasBears5235 }}